### ISSUE TITLE
[Odoo 10.0] ImportError: No module named xlsxwriter

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/docker-odoo-image#169]
I've seen that in Odoo 10.0 a python module is needed

In this case is `xlsxwriter`, see the bash log below to get it

```bash
2016-12-01 17:53:39,161 5621 INFO openerp_template odoo.modules.registry: module account_bank_statement_import: creating or updating database tables
2016-12-01 17:53:39,396 5621 INFO openerp_template odoo.modules.loading: loading account_bank_statement_import/account_bank_statement_import_view.xml
2016-12-01 17:53:39,446 5621 INFO openerp_template odoo.modules.loading: loading account_bank_statement_import/account_import_tip_data.xml
2016-12-01 17:53:39,448 5621 INFO openerp_template odoo.modules.loading: loading account_bank_statement_import/wizard/journal_creation.xml
2016-12-01 17:53:39,463 5621 INFO openerp_template odoo.modules.loading: loading account_bank_statement_import/demo/partner_bank.xml
2016-12-01 17:53:39,650 5621 INFO openerp_template odoo.modules.registry: module account_extension: creating or updating database tables
2016-12-01 17:53:39,686 5621 INFO openerp_template odoo.modules.loading: loading account_extension/views/account_report_menu_invisible.xml
2016-12-01 17:53:39,736 5621 INFO openerp_template odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [8626, 8769, 8765, 8767, 8482, 8629, 8773, 8475, 8752, 8748, 8743, 8738]
2016-12-01 17:53:39,737 5621 INFO openerp_template odoo.models.unlink: User #1 deleted ir.ui.menu records with IDs: [153, 152, 137, 168, 169, 171, 172, 170, 173, 130, 173, 167, 166]
2016-12-01 17:53:39,749 5621 INFO openerp_template odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [8634]
2016-12-01 17:53:39,754 5621 INFO openerp_template odoo.models.unlink: User #1 deleted ir.values records with IDs: [44]
2016-12-01 17:53:39,754 5621 INFO openerp_template odoo.models.unlink: User #1 deleted ir.actions.report.xml records with IDs: [214]
2016-12-01 17:53:39,777 5621 CRITICAL openerp_template odoo.modules.module: Couldn't load module account_reports
2016-12-01 17:53:39,777 5621 CRITICAL openerp_template odoo.modules.module: No module named xlsxwriter
2016-12-01 17:53:39,777 5621 ERROR openerp_template odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
File "/home/travis/odoo-10.0/odoo/modules/registry.py", line 78, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/travis/odoo-10.0/odoo/modules/loading.py", line 337, in load_modules
loaded_modules, update_module)
File "/home/travis/odoo-10.0/odoo/modules/loading.py", line 235, in load_marked_modules
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
File "/home/travis/odoo-10.0/odoo/modules/loading.py", line 122, in load_module_graph
load_openerp_module(package.name)
File "/home/travis/odoo-10.0/odoo/modules/module.py", line 367, in load_openerp_module
__import__('odoo.addons.' + module_name)
File "/home/travis/odoo-10.0/odoo/modules/module.py", line 81, in load_module
execfile(modfile, new_mod.__dict__)
File "/home/travis/enterprise/account_reports/__init__.py", line 4, in <module>
import models
File "/home/travis/enterprise/account_reports/models/__init__.py", line 4, in <module>
import account_report_context_common
File "/home/travis/enterprise/account_reports/models/account_report_context_common.py", line 5, in <module>
import xlsxwriter
ImportError: No module named xlsxwriter
```

### travis ci
![image](https://cloud.githubusercontent.com/assets/2961943/20805772/cbc0940e-b7bd-11e6-8e5b-b0d63db51472.png)

**Comment by osvalr** [comment]
@moylop260 where this module can be included?

**Comment by moylop260** [comment]
Fixed from https://github.com/Vauxoo/maintainer-quality-tools/commit/04e1c538067a576a6f8651904bac10556fc9a4e3
Rebuild please

**Comment by osvalr** [comment]
thank you @moylop260
