### ISSUE TITLE
Error when building image: setuptools pip wheel failed with error code 1

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/docker-odoo-image#309]
When the image is built the following error occurs:

```
Successfully installed linecache2-1.0.0 pyserial-3.4 python-slugify-1.2.5 slumber-0.7.1 traceback2-1.4.0 transifex-client-0.13.4 unittest2-1.1.0
Create the virtualenv using python3.3
Already using interpreter /usr/bin/python3.3
Using base prefix '/usr'
New python executable in /.repo_requirements/virtualenv/python3.3/bin/python3.3
Also creating executable in /.repo_requirements/virtualenv/python3.3/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /.repo_requirements/...hon3.3/bin/python3.3 - setuptools pip wheel:
  DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Looking in links: /usr/local/lib/python3.3/dist-packages, /usr/local/lib/python3.3/dist-packages/virtualenv_support, /usr/local/lib/python3.3/dist-packages/virtualenv_support
Collecting setuptools
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl
Collecting pip
  Cache entry deserialization failed, entry ignored
Collecting wheel
  Cache entry deserialization failed, entry ignored
wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
You are using pip version 7.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.3/dist-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/usr/local/lib/python3.3/dist-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.3/dist-packages/virtualenv.py", line 947, in create_environment
    download=download,
  File "/usr/local/lib/python3.3/dist-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python3.3/dist-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /.repo_requirements/...hon3.3/bin/python3.3 - setuptools pip wheel failed with error code 1
```

The complete log may be checked [here](https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/builds/b5yq4nfa9ugvbphwphxf5e/)

**Comment by luisg123v** [comment]
@moylop260 
I finally found the cause.

A few days ago, virtualenv 16.0 was released. According to [its change log](https://virtualenv.pypa.io/en/stable/changes/#id1), it upgrades wheel to 0.31.1. However, wheel has dropped support for Python 3.3 in [the previows version 0.31.0](https://pypi.org/project/wheel/0.31.0/).

Therefore, I'm going to freeze virtualenv version to `< 16.0` for Python 3.3, like we did for Python3.2:

https://github.com/Vauxoo/docker-odoo-image/blob/1c336a839bdc2b9c6dfe019dcb4e65eda5f847ab/odoo-shippable/scripts/build-image.sh#L168
